### PR TITLE
jxl-render: Rewrite EPF

### PR DESCRIPTION
**Pull request by tirr-c**

### CODE REVIEW

**Comment by Shnatsel** [comment]
Does the uninitialized output buffer significantly improve the benchmarks?

`vec![0; len];` is usually good enough because it requests already-zeroed memory from the OS, so you often don't have to pay the cost of a `memset()`.

I see the initialization is handled by non-trivial SIMD code, and is different for different codepaths, so it would be non-trivial to test. Failure to initialize the full output buffer would leak memory contents, which is a rather nasty security vulnerability that is [not uncommon](https://seclists.org/fulldisclosure/2013/Nov/83) in image decoders. And detecting it would rather difficult, since you would have to have a dedicated fuzzer with Memory Sanitizer in addition to the regular fuzzer, which is slow and requires a very large amount of memory. I've tried running that locally and the fuzzing speed drop is somewhere between 100x and 10,000x depending on the input, and it keeps OOMing even when I allow it 30GB of RAM. And all of this would also have to be repeated for every single SIMD codepath, so we'd have to separately run this on x86 and ARM! So it would be very difficult to test the absence of such vulnerabilities.

**Comment by tirr-c** [comment]
@Shnatsel I thought the memory allocator (or the OS) will give an already-zeroed memory region at first, but that was not the case; requesting uninitialized memory was significantly faster than `vec![0f32, n]` (especially on my aarch64 MacBook Pro). It took about 5% *of the entire decode time*, at least in my benchmark set.

I get what you are concerned about though, working with uninitialized buffers is quite tricky. It's definitely a safe choice to remove those `MaybeUninit`'s; maybe I can find a way to reuse buffers between various filters to avoid `MaybeUninit`.

**Comment by Shnatsel** [comment]
Ah, that is a sign of the initialized buffers being requested and freed frequently. It seems that these buffers are per-row, so that makes sense. Per-row buffers should be possible to initialize once and reuse; in the worst case you might have to keep two sets of them around, but IMO that's still better than dealing with uninit buffers. 

I feel the selling point of jxl-oxide is the safety, not 5% better performance. Especially considering that the reference implementation has great performance already, it's safety and security that it lacks.

**Comment by tirr-c** [comment]
Reverted uninit buffers, I think the penalty of zeroing out buffers is acceptable for now. This is my benchmark result against efc4a38:

<details>
<summary>Ryzen 5600X</summary>

```
nahida-motion.d1-e7/preferred-color
                        time:   [57.779 ms 57.926 ms 58.082 ms]
                        thrpt:  [63.469 Melem/s 63.640 Melem/s 63.802 Melem/s]
                 change:
                        time:   [-3.1414% -2.8008% -2.4874%] (p = 0.00 < 0.05)
                        thrpt:  [+2.5509% +2.8815% +3.2432%]
                        Performance has improved.
Found 6 outliers among 100 measurements (6.00%)
  6 (6.00%) high mild

starrail.d1-e6/preferred-color
                        time:   [55.691 ms 55.861 ms 56.046 ms]
                        thrpt:  [65.774 Melem/s 65.993 Melem/s 66.193 Melem/s]
                 change:
                        time:   [-7.2171% -6.7646% -6.3232%] (p = 0.00 < 0.05)
                        thrpt:  [+6.7500% +7.2554% +7.7785%]
                        Performance has improved.
Found 12 outliers among 100 measurements (12.00%)
  8 (8.00%) high mild
  4 (4.00%) high severe

genshin-cafe.d2-e6-epf2/preferred-color
                        time:   [105.22 ms 105.60 ms 106.03 ms]
                        thrpt:  [63.828 Melem/s 64.089 Melem/s 64.325 Melem/s]
                 change:
                        time:   [-11.963% -11.490% -10.981%] (p = 0.00 < 0.05)
                        thrpt:  [+12.335% +12.982% +13.588%]
                        Performance has improved.
Found 8 outliers among 100 measurements (8.00%)
  5 (5.00%) high mild
  3 (3.00%) high severe

genshin-cafe.d2-e6-epf3/preferred-color
                        time:   [111.88 ms 112.15 ms 112.46 ms]
                        thrpt:  [60.182 Melem/s 60.346 Melem/s 60.496 Melem/s]
                 change:
                        time:   [-16.441% -16.128% -15.810%] (p = 0.00 < 0.05)
                        thrpt:  [+18.778% +19.230% +19.675%]
                        Performance has improved.
Found 5 outliers among 100 measurements (5.00%)
  4 (4.00%) high mild
  1 (1.00%) high severe
```
</details>

<details>
<summary>MacBook Pro, M1 Max</summary>

```
nahida-motion.d1-e7/preferred-color
                        time:   [41.909 ms 41.989 ms 42.084 ms]
                        thrpt:  [87.596 Melem/s 87.794 Melem/s 87.962 Melem/s]
                 change:
                        time:   [+4.1428% +4.5644% +4.9600%] (p = 0.00 < 0.05)
                        thrpt:  [-4.7256% -4.3651% -3.9780%]
                        Performance has regressed.
Found 6 outliers among 100 measurements (6.00%)
  1 (1.00%) high mild
  5 (5.00%) high severe

starrail.d1-e6/preferred-color
                        time:   [42.397 ms 42.483 ms 42.599 ms]
                        thrpt:  [86.537 Melem/s 86.773 Melem/s 86.949 Melem/s]
                 change:
                        time:   [+4.4057% +4.8063% +5.2030%] (p = 0.00 < 0.05)
                        thrpt:  [-4.9456% -4.5859% -4.2198%]
                        Performance has regressed.
Found 4 outliers among 100 measurements (4.00%)
  4 (4.00%) high severe

genshin-cafe.d2-e6-epf2/preferred-color
                        time:   [66.409 ms 66.517 ms 66.629 ms]
                        thrpt:  [101.58 Melem/s 101.75 Melem/s 101.91 Melem/s]
                 change:
                        time:   [-6.1083% -5.8637% -5.6180%] (p = 0.00 < 0.05)
                        thrpt:  [+5.9524% +6.2289% +6.5056%]
                        Performance has improved.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild

genshin-cafe.d2-e6-epf3/preferred-color
                        time:   [71.257 ms 71.419 ms 71.591 ms]
                        thrpt:  [94.537 Melem/s 94.765 Melem/s 94.981 Melem/s]
                 change:
                        time:   [-7.5383% -7.1604% -6.8301%] (p = 0.00 < 0.05)
                        thrpt:  [+7.3308% +7.7126% +8.1529%]
                        Performance has improved.
Found 3 outliers among 100 measurements (3.00%)
  3 (3.00%) high mild
```
</details>

In general, it gets faster with more iterations of EPF.

Regarding buffer reuse: the only per-row buffer in EPF is the filter strength (sigma) data. We can't use per-row output buffer easily, because the filter references adjacent rows and is multithreaded. Instead, the extra image-sized buffer is allocated and two buffers are swapped when needed.

**Pull request merged**
