### PR TITLE
Optimize noise rendering

### LINKED ISSUE #399: Rendering noise is very slow
When decoding a GNOME desktop background, jxl-oxide takes more than 3x longer to decode the file compared to `djxl` v0.8.1

jxl-oxide spends 71% of the time in `jxl_render::features::noise::render_noise` on the main thread. You can see it for yourself on the profile: https://share.firefox.dev/3ZQgu1s

This issue is a blocker for GNOME's [`glycin`](https://gitlab.gnome.org/GNOME/glycin), the backend for GNOME's default image viewer and [soon the image library to be used for everything GNOME](https://gitlab.gnome.org/GNOME/Initiatives/-/issues/53) from switching from libjxl to jxl-oxide.

### PR DESCRIPTION
**Pull request by tirr-c**
Resolves #399 

~~TODO: avoid zerofilling buffer~~ There's some zerofilling when doing convolution, but I'm going to leave it as is for now

### CODE REVIEW

**Comment by Shnatsel** [comment]
hyperfine reports a 1.85x speedup on my machine, from 1.020 s to 550ms!

And yes, eliminating `memset` would be a massive improvement. It now accounts for 44% of the time spent on the single straggler thread: https://share.firefox.dev/4iO65MA

**Comment by Shnatsel** [comment]
If I disable the `mimalloc` feature on jxl-oxide-cli which makes it use the default glibc allocator on my Linux machine, I get 416ms decoding time on this OR for the sample image from #399 as opposed to 550ms with `mimalloc`.

Profile with mimalloc: https://share.firefox.dev/3Du3jvO

Profile without mimalloc: https://share.firefox.dev/4gmv1cq

I believe the glibc allocator requests zeroed memory from the kernel instead of performing a userspace memset immediately. The kernel then lazily zeroes memory on demand. This spreads the cost of memset across all the worker threads instead of doing all the memsets on the thread that allocates memory.

Then again, the glibc allocator is the best-case system allocator. If it's possible to eliminate the remaining memsets or manually shift their allocation to other threads, the choice of allocator will stop affecting memset performance.

**Comment by tirr-c** [comment]
Interesting, mimalloc is slower than glibc at one-shot but faster when repeated.

Default (`--features rayon,mimalloc`):
```
2024-12-24T15:09:47.656139Z  INFO jxl_oxide_cli::decode: Image dimension: 4096x4096
2024-12-24T15:09:47.656164Z  INFO jxl_oxide_cli::decode: Running 20 repetitions
2024-12-24T15:09:57.751485Z  INFO jxl_oxide_cli::decode: Geomean: 497.770 ms (33.705 MP/s)
2024-12-24T15:09:57.751518Z  INFO jxl_oxide_cli::decode: Range: [477.590 ms, 724.424 ms] ([23.159 MP/s, 35.129 MP/s])
2024-12-24T15:09:57.751524Z  INFO jxl_oxide_cli::decode: No output path specified, skipping output encoding
```

`--no-default-features --features rayon`:
```
2024-12-24T15:09:26.159571Z  INFO jxl_oxide_cli::decode: Image dimension: 4096x4096
2024-12-24T15:09:26.159598Z  INFO jxl_oxide_cli::decode: Running 20 repetitions
2024-12-24T15:09:39.059989Z  INFO jxl_oxide_cli::decode: Geomean: 618.972 ms (27.105 MP/s)
2024-12-24T15:09:39.060035Z  INFO jxl_oxide_cli::decode: Range: [604.212 ms, 683.450 ms] ([24.548 MP/s, 27.767 MP/s])
2024-12-24T15:09:39.060041Z  INFO jxl_oxide_cli::decode: No output path specified, skipping output encoding
```

**Comment by Shnatsel** [comment]
Yeah, glibc allocator not being faster on repeated runs makes sense. It doesn't release the memory back to the OS to reuse it. But when it reuses it it needs to zero-fill it up front, like mimalloc always does.

**Comment by Shnatsel** [comment]
Thank you for optimizing this so quickly!

**Pull request merged**
